---
- name: copy_join_conf
  template:
    src: join.conf.j2
    dest: "{{ kubeadm.join.config_file }}"
    owner: root
    group: root
    mode: 0440

- include_tasks: reset.yml
# reimport cert wipe by kubeadm reset...
- import_tasks: certs.yml

- name: run_kubeadm_join
  command: "kubeadm join --config {{ kubeadm.join.config_file }}  --skip-phases=\"{{ kubeadm.join.skip_phases }}\" -v{{ kubeadm.log_level }}"
  notify: create_join_witness_file
  register: run_kubeadm_join

- debug:
    var: run_kubeadm_join

- meta: flush_handlers

- include_tasks: join/check.yml
  when: run_kubeadm_join is succeeded

- include_tasks: join/rm_conf.yml
