---
- name: disable_zram
  service:
    name: "{{ item }}"
    state: stopped
    enabled: False
  ignore_errors: true
  notify:
    - disable_swap
  with_items:
    - zram-config
    - armbian-zram-config
  when:
    - board_type is defined
    - board_type == "rock64"

- name: unmount_swap
  mount:
    path: /swap
    state: unmounted

- name: is_swap_in_fstab
  shell: "grep -Ev '^#' /etc/fstab | grep -q swap"
  register: is_swap_in_fstab
  ignore_errors: true

- name: comment_swap_fstab_entry
  shell: "sed -i 's/^[^#]*swap*/#&/' /etc/fstab"
  when:
    - is_swap_in_fstab.rc == 0

- name: is_any_swap_mounted
  shell: "cat /proc/swaps | grep -qv 'Filename'"
  notify:
    - disable_swap
  register: swap_mounted
  ignore_errors: true
  changed_when: swap_mounted.rc == 0
