---
- name: set_sysctl_prereq
  template:
    src: 90-sysctl-kubernetes.conf
    dest: /etc/sysctl.d/90-kubernetes.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - reload_sysctl

- name: set_modprobe_prereq
  template:
    src: modeprobe-kubernetes.conf
    dest: /etc/modules-load.d/kubernetes.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart_systemd_modules_load

- import_tasks: ipvs.yml
  when: kubernetes_network_req.ipvs

- import_tasks: ebpf.yml
  when: kubernetes_network_req.ebpf

# just to be sure
- name: run_sysctl_reload
  command: "sysctl --system"
  changed_when: false
- name: run_systemd_modules_load
  command: "systemctl restart systemd-modules-load.service"
  changed_when: false
